### ISSUE TITLE
installation issues...

### ISSUE THREAD

**Issue by fenix011** [mzacho/claudia#2]
While (after cloning the package in /lisp folder ... i'm evaluating  ,

```
;; instalar paquetes
;;

(use-package claudia ;; Anthropic 's assistant - Claude https://github.com/mzacho/claudia
  :load-path "~/.emacs.d/lisp/claudia"
  :ensure nil) ;; <- nil as it is manual installation

(setq claudia-api-key "sk-ant-api-XXXXXXXXXXXXXXXXX-YYYYYYYYYYYYYYYY-ZZZZZZ")
(setq claudia-organization-id "Librebits")
(with-eval-after-load 'claudia
  (global-set-key (kbd "C-x c") claudia-global-map))
```

but no joy... umh.  No 'claudia' comands available, ... 

What am i missing ? thX !

**Comment by mzacho** [comment]
You can install it from melpa now, see the readme :) thanks for trying claudia out, I'd appreciate if you'd continue to report any issues you find!

**Comment by fenix011** [comment]
BTW, did you knew about Alvaro's / Xenodium.com ... 'chatgpt-shell'

it does Claude too, now. FYI

**Comment by mzacho** [comment]
I've tried it briefly - the plan is to have claudia integrate more deeply with the builtin emacs functions in the long run, rather than just providing `claudia-chat` mode. I recently did a big refactoring where I added `claudia-mode`, which updates the project knowledge of the current project with recently visited buffers.

**Comment by fenix011** [comment]
oh, Biutiful... nice to know !
