### ISSUE TITLE
Issue in doom emacs

### ISSUE THREAD

**Issue by oatmealm** [mzacho/claudia#4]
Can't install on doom emacs. This error show up with a simple import command of the module.

```
(package! claudia)
```

```
x There was an unexpected runtime error
    Message: Symbol's value as variable is void
    Details: (claudia-gh-map)
    Backtrace:
      (define-key map (kbd "g") claudia-gh-map)
      (let ((map (make-sparse-keymap))) (define-key map (kbd "p") 'claudia-create-project) (define-key map (kbd "c") 'claudia-create-chat) (define-key map (kbd "k") 'claudia-clear-context) (define-key map (kbd "q") 'claudia-query) (define-key map (kbd "l") 'claudia-list-chats) (define-key map (kbd "s") 'claudia-send-visiting-buffer) (define-key map (kbd "e") 'claudia-explain-region) (define-key map (kbd "w") 'claudia...
      (defvar claudia-global-map (let ((map (make-sparse-keymap))) (define-key map (kbd "p") 'claudia-create-project) (define-key map (kbd "c") 'claudia-create-chat) (define-key map (kbd "k") 'claudia-clear-context) (define-key map (kbd "q") 'claudia-query) (define-key map (kbd "l") 'claudia-list-chats) (define-key map (kbd "s") 'claudia-send-visiting-buffer) (define-key map (kbd "e") 'claudia-explain-region) (define...
      (load-with-code-conversion "/home/xxx/.config/emacs/.local/straight/build-29.4/claudia/claudia-autoloads.el" "/home/xxx/.config/emacs/.local/straight/build-29.4/claudia/claudia-autoloads.el" nil t)
      (load "/home/xxx/.config/emacs/.local/straight/build-29.4/claudia/claudia-autoloads.el" nil nomessage)
      (progn (load autoloads-file nil 'nomessage))
      (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomessage)))
      (let ((autoloads-file (straight--autoloads-file package))) (if (file-exists-p autoloads-file) (progn (load autoloads-file nil 'nomessage))))
      (straight--load-package-autoloads "claudia")
      (let ((name (symbol-name package))) (add-to-list 'load-path (directory-file-name (straight--build-dir name))) (straight--load-package-autoloads name))
      (let ((package (car tail))) (straight-register-package package) (let ((name (symbol-name package))) (add-to-list 'load-path (directory-file-name (straight--build-dir name))) (straight--load-package-autoloads name)) (setq tail (cdr tail)))
      (while tail (let ((package (car tail))) (straight-register-package package) (let ((name (symbol-name package))) (add-to-list 'load-path (directory-file-name (straight--build-dir name))) (straight--load-package-autoloads name)) (setq tail (cdr tail))))
GNU Emacs     v29.4            nil
Doom core     v3.0.0-pre       HEAD -> master 48d04330 2024-11-04 20:44:35 -0500
Doom modules  v24.12.0-pre     HEAD -> master 48d04330 2024-11-04 20:44:35 -0500
```

**Comment by mzacho** [comment]
Thanks for reporting this. I don't use doom emacs myself, and unfortunately I'm unable to install it to reproduce this issue, since it's not packaged for my distro (nixos).

I can see that doom emacs has their own package manager which uses `straight.el`, the issue seems to be related to how `straight.el` autoloads `claudia.el`. I've pushed a possible fix to the branch `fix/doom`, would you mind seeing if that works in doom by installing claudia [straight from this branch](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#installing-packages-from-external-sources):

```elisp
(package! claudia :recipe
  (:host github
   :repo "mzacho/claudia"
   :branch "fix/doom"))
``` 
?

If not you can experiment with your own fork and see if you can get it to work :)

**Comment by oatmealm** [comment]
I initially installed from your repo and switched back to melpa thinking there must be some regression. I'll test the branch asap and report. Thanks!

**Comment by oatmealm** [comment]
Same problem, I'm afraid.  
Double-checked autoload was removed:

```
cat claudia.el | grep -B3 claudia-global-map
    map)
  "Keymap for Claudia GitHub-related commands.")

(defvar claudia-global-map
```

**Comment by mzacho** [comment]
Alright, thanks - what if you fork the project and remove the two keymaps?

**Comment by oatmealm** [comment]
I'll play around with thanks!

**Comment by mzacho** [comment]
I recently did a big refactoring, can you check if this is still a problem @oatmealm?

**Comment by oatmealm** [comment]
Hi there. I've switched to a custom config since. 

I'm able to activate the mode, list projects and chats.

One small issue was centered-cursor-mode, which needs to be installed to use the example config.

Couple of observations:

1. When starting a new chat, it's awkward to have to title it and then write the prompt, which are often the same.

2. The name of the documents created in the project workspace are convoluted `claudia-buffer:/home/xxxx/Nextcloud/know...`

3. If I understand it correctly, I would need to upload each document interactively while in chat mode? If so, would be able to batch upload them into the project at the start of a chat?

**Comment by oatmealm** [comment]
Another issue, display of non-latin scripts... clearly Emacs has an amazing multilingual support, so I'm not sure why it's displaying unicode code points in this case.

![image](https://github.com/user-attachments/assets/3b034be6-67fa-4047-8a17-fdfa79cec229)
![image](https://github.com/user-attachments/assets/eb576cc9-56c1-43f3-a542-6cb19e91acfa)

**Comment by mzacho** [comment]
Thanks for the feedback, appreciate it

> 2. The name of the documents created in the project workspace are convoluted `claudia-buffer:/home/xxxx/Nextcloud/know...`

I'm wondering when/ why this is a problem for you? I'm prefixing project docs with claudia-buffer so they can recognized as "claudia managed project docs" in order to update claudia--recent-buffers-alist when switching projects.

The absolute path to the file is added as part of the name so the old doc can be removed whenever a buffer is saved to its file.

If you have a suggestion on a better way to do this i'm all ears :)

> 3. If I understand it correctly, I would need to upload each document interactively while in chat mode? If so, would be able to batch upload them into the project at the start of a chat?

Currently you can upload the entire content of a buffer to Claude.ai as a project document in 2 ways:

- By enabling claudia-mode, which will automatically update the project knowledge with your recently visited buffers (using claudia--window-change-hook and claudia--after-save-hook)
- Manually using claudia-add-buffer-to-project-knowledge

You can also upload part of a buffer manually with claudia-add-region-to-knowledge.

Documents can be deleted one at a time with claudia-delete-project-knowledge.

**Comment by mzacho** [comment]
>     1. When starting a new chat, it's awkward to have to title it and then write the prompt, which are often the same.

Added a new function `claudia-create-chat` in 6905b1c which uses `claudia-default-chat-name` that you can customize

**Comment by mzacho** [comment]
> Another issue, display of non-latin scripts... clearly Emacs has an amazing multilingual support, so I'm not sure why it's displaying unicode code points in this case.

Yes, this is unfortunate. I'll open this as a separate issue and look more into this in the near future.

**Comment by mzacho** [comment]
Dont think this is an issue anymore
